name: Continuous Deployment

on:
  push:
    branches: ["main"]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g http-server
          npm install eslint@8.56.0 eslint-config-airbnb-base@15 eslint-plugin-import@2.29.1 mocha chai wait-on --save-dev

      - name: Fix ESLint permissions
        run: chmod +x ./node_modules/.bin/eslint

      - name: Run tests
        run: |
          http-server -p 8080 . > /dev/null 2>&1 &
          sleep 5
          npx wait-on http://localhost:8080/test.html

      - name: Lint code
        run: npx eslint script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
